# Generated by Django 4.2.2 on 2023-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recepie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
