# Generated by Django 4.2.2 on 2023-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recepie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_image', models.ImageField(upload_to='pdf_fol')),
            ],
        ),
        migrations.DeleteModel(
            name='Recepie',
        ),
    ]
