# Generated by Django 4.2.2 on 2023-06-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_pdf1_delete_recepie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf1',
            name='receipe_image',
            field=models.FileField(upload_to='pdf_fol'),
        ),
    ]
